name: Deploy a branch as a snapshot version.

on:
  workflow_dispatch:

# Cancel previous jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Normalize branch name
      id: normalize-branch-name
      uses: ./.github/actions/normalize-branch-name
    - name: Set version
      run: mvn -B versions:set -DnewVersion=0.0.0.${{ steps.normalize-branch-name.outputs.normalized }}-SNAPSHOT
    - uses: ./.github/actions/maven-build
      with:
        build-command: deploy  # Deploy a snapshot build of main
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
